### PR TITLE
Some more options to handle text

### PR DESCRIPTION
**Pull request by aliab**
I've added some modification and add these things:

1. Ability to change typeface of menu item
2. Ability to change text size (in both default and selected) of menu item
3. Ability to add message in string over menu (like numbers, but accept String)

---
updated commit:
1. update Travis config
2. ability to change colors on-the-fly

### CODE REVIEW

**Comment by tyzlmjj** [comment]
I've merged your request into the dev branch. Probably in the next release. But I do not think these properties are necessary.

**Comment by aliab** [comment]
Thank you, maybe but I extend your library base of required things in my in-developing app. so i think it is very good that developer have these options with your great library.

**Comment by tyzlmjj** [comment]
I recently updated version 2. The code is completely different

**Comment by Omid-naji** [comment]
how can i change typeface?

**Comment by tyzlmjj** [comment]
In the latest version, the font is fixed in the Material mode. But you can set whatever you want in Custom mode.

**Pull request closed without merging**
